#!/bin/sh

# This script is unlikely to be of any use to anyone other than me since
# it depends on the location of files on my specific system.
# But it does in a sense "document" where the various binary files
# come from that this project starts with.
# Tom Trebisky  12-1-2018

ATF="../../pc2/U-Boot/arm-trusted-firmware"

###cp $ATF/build/sun50iw1p1/debug/bl31.bin .
cp $ATF/build/sun50iw1p1/debug/bl31/bl31.elf .

UBOOT="../../pc2/U-Boot/u-boot-2018.09"

# Someday we will build this from source
cp $UBOOT/tools/mkimage .
exit

cp $UBOOT/spl/u-boot-spl u-boot-spl.elf
cp $UBOOT/u-boot u-boot.elf
#cp $UBOOT/board/sunxi/mksunxi_fit_atf.sh .
cp $UBOOT/arch/arm/dts/sun50i-h5-orangepi-pc2.dtb .

# Valuable information to keep with all of this.
cp $UBOOT/board/sunxi/README.sunxi64 .

#cp $UBOOT/tools/mksunxiboot.c .
#cp $UBOOT/arch/arm/include/asm/arch-sunxi/spl.h .


# THE END
